apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  labels:
    app: cnkt-event-listener
  name: cnkt-event-listener
spec:
  serviceAccountName: pipeline
  triggers:
    - name: mq-infra-dev
      interceptors:
        - cel:
            filter: header.match('X-GitHub-Event', 'push') && body.ref == 'refs/heads/qm1-client-engineering-gitops-h' && body.repository.full_name == 'client-engineering-gitops-h/mq-infra'
      bindings:
        - ref: cnkt-trigger-binding
      template:
        ref: mq-infra-dev
    - name: mq-spring-app-dev
      bindings:
        - ref: cnkt-trigger-binding
      template:
        ref: mq-spring-app-dev
      
