apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: multi-tenancy-gitops
    group: pipeline
    type: git
  name: gitops-repo
data:
  branch: master
  host: github.com
  org: techfest-pp
  owner: techfest-pp
  parentdir: .
  protocol: https
  repo: multi-tenancy-gitops-apps
  url: https://github.com/techfest-pp/multi-tenancy-gitops-apps.git
